### ISSUE TITLE
[FR] Export to PNG on Node.js

### ISSUE THREAD

**Issue by NightMachinary** [sallar/github-contributions-canvas#30]
I tried doing this myself (using https://github.com/Automattic/node-canvas), but I couldn't get it to work:
```
#!/usr/bin/env node

const fs = require('fs')
const { createCanvas, loadImage } = require('canvas')

const width = 1200
const height = 630

const canvas = createCanvas(width, height)

const { drawContributions } = require("github-contributions-canvas")

contributionData = {
  "years": [
    {
      "year": "2018",
      "total": 11,
      "range": {
        "start": "2018-01-01",
        "end": "2018-12-31"
      }
    }
  ],
  "contributions": [
      {
      "date": "2018-01-05",
      "count": 0,
      "color": "#ebedf0",
      "intensity": "0"
    },
    {
      "date": "2018-01-04",
      "count": 2,
      "color": "#9be9a8",
      "intensity": "1"
    },
    {
      "date": "2018-01-03",
      "count": 0,
      "color": "#ebedf0",
      "intensity": "0"
    },
    {
      "date": "2018-01-02",
      "count": 9,
      "color": "#216e39",
      "intensity": "4"
    },
    {
      "date": "2018-01-01",
      "count": 0,
      "color": "#ebedf0",
      "intensity": "0"
    }
  ]
}


drawContributions(canvas, {
  data: contributionData,
  username: "myusername",
  themeName: "standard",
  footerText: "Made by @sallar - github-contributions.now.sh"
});

const buffer = canvas.toBuffer('image/png')
fs.writeFileSync('./test.png', buffer)
```

```
/usr/local/lib/node_modules/github-contributions-canvas/dist/index.js:65
var scaleFactor = window.devicePixelRatio || 1;
                  ^

ReferenceError: window is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/github-contributions-canvas/dist/index.js:65:19)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/evar/scripts/javascript/activityChart.js:11:31)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
```

**Comment by sallar** [comment]
Will fix that! Thank you
